import { NextRequest } from "next/server";
import {
  validateAgentKey,
  unauthorizedResponse,
  autocodeStore,
  AutocodeRequest,
  AutocodeResult,
  generateId,
  agentSettings,
} from "@/lib/agent";

// GET /api/agent/autocode — list generated code artifacts
export async function GET(request: NextRequest) {
  if (!validateAgentKey(request)) return unauthorizedResponse();

  return Response.json({ artifacts: autocodeStore, total: autocodeStore.length });
}

// POST /api/agent/autocode — submit an autocode instruction
export async function POST(request: NextRequest) {
  if (!validateAgentKey(request)) return unauthorizedResponse();

  if (!agentSettings.autocode.enabled) {
    return Response.json(
      { error: "Autocode is currently disabled in agent settings" },
      { status: 403 }
    );
  }

  let body: AutocodeRequest;
  try {
    body = await request.json();
  } catch {
    return Response.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  if (!body.instruction || !body.target) {
    return Response.json(
      { error: "Fields 'instruction' and 'target' are required" },
      { status: 400 }
    );
  }

  // Generate code scaffold based on target type
  const generated = generateCodeScaffold(body);

  autocodeStore.push(generated);

  return Response.json(
    {
      artifact: generated,
      autoApplied: agentSettings.autocode.autoApply,
      requiresApproval: agentSettings.autocode.approvalRequired,
    },
    { status: 201 }
  );
}

// PATCH /api/agent/autocode — mark artifact as applied
export async function PATCH(request: NextRequest) {
  if (!validateAgentKey(request)) return unauthorizedResponse();

  let body: { id: string };
  try {
    body = await request.json();
  } catch {
    return Response.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  const artifact = autocodeStore.find((a) => a.id === body.id);
  if (!artifact) {
    return Response.json({ error: "Artifact not found" }, { status: 404 });
  }

  artifact.appliedAt = new Date().toISOString();

  return Response.json({ artifact });
}

// ─── Code scaffold generator ──────────────────────────────────────────────────

function generateCodeScaffold(req: AutocodeRequest): AutocodeResult {
  const id = generateId("AC");
  const now = new Date().toISOString();

  const templates: Record<AutocodeRequest["target"], { lang: string; code: string }> = {
    component: {
      lang: "tsx",
      code: `// AUTO-GENERATED by OpenClaw — ${now}\n// Instruction: ${req.instruction}\n\nexport function GeneratedComponent() {\n  return (\n    <div className="bg-gray-900 border border-gray-800 rounded-xl p-5">\n      {/* TODO: implement — ${req.instruction} */}\n    </div>\n  );\n}`,
    },
    query: {
      lang: "sql",
      code: `-- AUTO-GENERATED by OpenClaw — ${now}\n-- Instruction: ${req.instruction}\n\nSELECT\n  -- TODO: define columns based on: ${req.instruction}\nFROM jacqes_data\nWHERE active = true\nORDER BY created_at DESC;`,
    },
    report: {
      lang: "ts",
      code: `// AUTO-GENERATED by OpenClaw — ${now}\n// Instruction: ${req.instruction}\n\nexport async function generateReport(params: Record<string, unknown>) {\n  // TODO: implement report — ${req.instruction}\n  return { title: "Generated Report", data: [], generatedAt: new Date().toISOString() };\n}`,
    },
    dashboard: {
      lang: "tsx",
      code: `// AUTO-GENERATED by OpenClaw — ${now}\n// Instruction: ${req.instruction}\n\nexport default function GeneratedDashboard() {\n  return (\n    <main className="p-6 space-y-6">\n      <h1 className="text-xl font-bold text-white">Generated Dashboard</h1>\n      {/* TODO: build — ${req.instruction} */}\n    </main>\n  );\n}`,
    },
    config: {
      lang: "json",
      code: `// AUTO-GENERATED by OpenClaw — ${now}\n{\n  "_instruction": "${req.instruction}",\n  "_generatedAt": "${now}"\n}`,
    },
    migration: {
      lang: "ts",
      code: `// AUTO-GENERATED by OpenClaw — ${now}\n// Migration: ${req.instruction}\n\nexport async function up() {\n  // TODO: migration up — ${req.instruction}\n}\n\nexport async function down() {\n  // TODO: migration down — ${req.instruction}\n}`,
    },
  };

  const tpl = templates[req.target];

  return {
    id,
    instruction: req.instruction,
    target: req.target,
    code: tpl.code,
    language: tpl.lang,
    description: `[${req.target.toUpperCase()}] ${req.instruction}`,
    generatedAt: now,
  };
}
